name: amazon_clone
description: Amazon Clone Project
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  provider: ^6.0.5
  shared_preferences: ^2.2.1
  badges: ^3.1.2
  flutter_rating_bar: ^4.0.1
  font_awesome_flutter: ^10.5.0
  dotted_border: ^2.1.0
  cached_network_image: ^3.2.3
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/applepay.json
    - assets/gpay.json 